export const GET_REPOS_LIST = 'GET_REPOS_LIST';
export const SAVE_REPOS_LIST = 'SAVE_REPOS_LIST';
export const GET_REPO_BRANCH_LIST = 'GET_REPO_BRANCH_LIST';
export const SAVE_REPO_BRANCH_LIST = 'SAVE_REPO_BRANCH_LIST';
export const GET_REPO_BRANCH_COMMIT_LIST = 'GET_REPO_BRANCH_COMMIT_LIST';
export const SAVE_REPO_BRANCH_COMMIT_LIST = 'SAVE_REPO_BRANCH_COMMIT_LIST';
